# Generated by Django 5.1.1 on 2024-11-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
