# Generated by Django 5.1.1 on 2024-11-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at']},
        ),
    ]
